import { useCallback, useEffect, useState } from 'react';
import { ArrowLeft, Download, Plus, Search, Users, CheckCircle2, Heart, LogOut, Pencil, Trash2, X, RefreshCw } from 'lucide-react';
import { demo, supabase, listRsvps, adminSave, adminDelete } from './api';
import { blankRsvp, summarize, sides, groups, csv, download } from './domain';
import RsvpForm from './RsvpForm';
export default function Admin() {
  const [authorized,setAuthorized] = useState(demo), [checking,setChecking] = useState(!demo && !!supabase);
  const [email,setEmail] = useState(''), [password,setPassword] = useState(''), [error,setError] = useState('');
  const [rows,setRows] = useState([]), [loading,setLoading] = useState(false), [loginBusy,setLoginBusy] = useState(false);
  const [query,setQuery] = useState(''), [status,setStatus] = useState(''), [side,setSide] = useState(''), [group,setGroup] = useState('');
  const [edit,setEdit] = useState(null), [deleting,setDeleting] = useState(null), [deleteBusy,setDeleteBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(''); try { setRows(await listRsvps()); } catch { setError('โหลดรายชื่อไม่สำเร็จ กรุณาลองใหม่'); } finally { setLoading(false); } }, []);
  useEffect(() => {
    if (!supabase || demo) return;
    let active = true, version = 0;
    const check = async session => {
      const request = ++version;
      if (!session) { if (active) { setAuthorized(false); setRows([]); setChecking(false); } return; }
      setChecking(true);
      const { data,error: roleError } = await supabase.from('admin_users').select('user_id').eq('user_id',session.user.id).maybeSingle();
      if (!active || request !== version) return;
      setAuthorized(!!data && !roleError); setChecking(false);
      if (!data || roleError) { setRows([]); setError('บัญชีนี้ไม่มีสิทธิ์ผู้จัดงาน กรุณาติดต่อเจ้าของระบบ'); }
    };
    supabase.auth.getSession().then(({data})=>check(data.session)).catch(()=>{ if(active) {setChecking(false);setError('ตรวจสอบการเข้าสู่ระบบไม่สำเร็จ');} });
    const {data:{subscription}} = supabase.auth.onAuthStateChange((_event,session)=>{ setTimeout(()=>{if(active) check(session);},0); });
    return ()=>{active=false;subscription.unsubscribe();};
  }, []);
  useEffect(() => { if (authorized) load(); }, [authorized,load]);
  const stats = summarize(rows);
  const visible = rows.filter(r => (!status || r.attendance_status === status) && (!side || r.host_side === side) && (!group || r.guest_group === group) && [r.full_name,r.phone,r.email,r.group_detail,r.remark].some(v=>String(v||'').toLowerCase().includes(query.trim().toLowerCase())));
  async function login(e) { e.preventDefault(); if (!supabase) return; setLoginBusy(true);setError('');try {const {error:e} = await supabase.auth.signInWithPassword({email,password});if(e) setError('อีเมลหรือรหัสผ่านไม่ถูกต้อง หรือยังไม่ยืนยันบัญชี');} catch {setError('เชื่อมต่อไม่สำเร็จ กรุณาลองใหม่');} finally {setLoginBusy(false);} }
  if (checking) return <main className="login-page"><p role="status">กำลังตรวจสอบสิทธิ์…</p></main>;
  if (!authorized) return <main className="login-page"><a href="#home" className="text-link"><ArrowLeft size={16}/>กลับหน้า E-Card</a><div className="login-card"><div className="eyebrow">FOR THE HOSTS</div><h1>ยินดีต้อนรับ<br/>ผู้จัดงาน</h1><p>เข้าสู่ระบบเพื่อดูและจัดการคำตอบรับ</p>{!supabase ? <p className="error">ยังไม่ได้ตั้งค่า Supabase โปรดดูคู่มือใน README</p> : <form onSubmit={login}><label>อีเมล<input type="email" autoComplete="username" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>รหัสผ่าน<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error && <p className="error" role="alert">{error}</p>}<button className="button" disabled={loginBusy}>{loginBusy ? 'กำลังเข้าสู่ระบบ…' : 'เข้าสู่ระบบ'}</button></form>}</div></main>;
  return <div className="admin-page">{demo && <div className="demo-banner">แอดมินโหมดทดลอง · เฉพาะข้อมูลในเบราว์เซอร์นี้ ไม่มีข้อมูลแขกจริงจากฐานข้อมูล</div>}<header className="admin-header"><a className="brand" href="#home">Our wedding<small>HOST DASHBOARD</small></a><div className="header-actions"><a href="#home" className="text-link"><ArrowLeft size={15}/>ดู E-Card</a>{!demo && <button className="text-link" onClick={async()=>{const {error:e}=await supabase.auth.signOut();if(e){setError('ออกจากระบบไม่สำเร็จ กรุณาลองใหม่');return;}setAuthorized(false);setRows([]);}}><LogOut size={16}/>ออกจากระบบ</button>}</div></header><main className="admin-main"><div className="admin-title"><div><div className="eyebrow">EVERY GUEST, EVERY MEMORY</div><h1>รายชื่อคนสำคัญ</h1><p>จัดการคำตอบรับ เตรียมพร้อมสำหรับวันของคุณ</p></div><button className="button" onClick={()=>setEdit({...blankRsvp})}><Plus size={17}/>เพิ่มคำตอบรับ</button></div>
    <div className="stats-grid">{[[Users,'ผู้มาร่วมงาน',stats.people,'คน'],[CheckCircle2,'ตอบรับเข้าร่วม',stats.attending,'รายการ'],[Heart,'คำตอบรับทั้งหมด',stats.total,'รายการ'],[Users,'ไม่สามารถเข้าร่วม',stats.declined,'รายการ']].map(([Icon,label,value,unit])=><article className="stat-card" key={label}><div><span>{label}</span><Icon size={18}/></div><strong>{value.toLocaleString()}<small>{unit}</small></strong></article>)}</div>
    <div className="summary-grid"><section className="summary-card"><h2>ผู้เข้าร่วมแยกตามฝั่ง</h2>{stats.sides.map(s=><div className="bar-row" key={s.label}><span>{s.label}</span><div className="bar-track"><i style={{width:`${stats.people ? s.count/stats.people*100 : 0}%`}}/></div><b>{s.count}</b></div>)}</section><section className="summary-card"><h2>ผู้เข้าร่วมแยกตามกลุ่ม</h2><div className="group-summary">{stats.groups.map(g=><div key={g.label}><span>{g.label}</span><b>{g.count}</b></div>)}</div></section></div>
    <section className="guest-panel"><div className="panel-heading"><h2>คำตอบรับทั้งหมด <span>{rows.length}</span></h2><div><button className="text-link" onClick={load} disabled={loading} aria-label="โหลดข้อมูลใหม่"><RefreshCw size={16}/></button><button className="text-link" disabled={!visible.length} onClick={()=>download(csv(visible),'wedding-rsvp.csv','text/csv;charset=utf-8')}><Download size={16}/>ส่งออก CSV ({visible.length})</button></div></div><div className="filters"><label className="search-field"><Search size={17}/><input aria-label="ค้นหารายชื่อ" placeholder="ค้นหาชื่อ เบอร์โทร หรือข้อความ…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="กรองสถานะ" value={status} onChange={e=>setStatus(e.target.value)}><option value="">ทุกสถานะ</option><option value="attending">เข้าร่วม</option><option value="declined">ไม่เข้าร่วม</option></select><select aria-label="กรองฝั่งเจ้าภาพ" value={side} onChange={e=>setSide(e.target.value)}><option value="">ทุกฝั่ง</option>{Object.entries(sides).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><select aria-label="กรองกลุ่มแขก" value={group} onChange={e=>setGroup(e.target.value)}><option value="">ทุกกลุ่ม</option>{groups.map(g=><option key={g}>{g}</option>)}</select></div>{error && <p className="error" role="alert">{error}</p>}{loading ? <p className="empty-state" role="status">กำลังโหลดรายชื่อ…</p> : !visible.length ? <div className="empty-state"><Users size={32}/><h3>{rows.length ? 'ไม่พบรายชื่อที่ตรงกับการค้นหา' : 'รอคำตอบจากคนสำคัญ'}</h3><p>{rows.length ? 'ลองเปลี่ยนคำค้นหาหรือตัวกรอง' : 'คำตอบ RSVP จะแสดงที่นี่เมื่อแขกส่งแบบฟอร์ม'}</p></div> : <div className="table-scroll"><table><thead><tr><th>ชื่อ / ช่องทางติดต่อ</th><th>สถานะ</th><th>ฝั่ง / กลุ่ม</th><th>จำนวน</th><th>หมายเหตุ</th><th>จัดการ</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><strong>{r.full_name}</strong><small>{[r.phone,r.email].filter(Boolean).join(' · ') || '—'}</small></td><td><span className={`badge ${r.attendance_status}`}>{r.attendance_status === 'attending' ? 'เข้าร่วม' : 'ไม่เข้าร่วม'}</span></td><td>{sides[r.host_side]}<small>{r.guest_group}{r.group_detail && ` · ${r.group_detail}`}</small></td><td>{r.guest_count} คน</td><td className="remark-cell">{r.remark || '—'}</td><td><div className="row-actions"><button aria-label={`แก้ไข ${r.full_name}`} onClick={()=>setEdit(r)}><Pencil size={16}/></button><button aria-label={`ลบ ${r.full_name}`} onClick={()=>setDeleting(r)}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>}</section><p className="fine-print">สรุปจำนวนคนจากคำตอบที่ระบุว่าเข้าร่วม · CSV ส่งออกตามตัวกรองที่เลือก</p></main>
    {edit && <div className="modal-backdrop"><section className="edit-modal" role="dialog" aria-modal="true" aria-label="แก้ไขคำตอบรับ"><button className="close-modal" aria-label="ปิด" onClick={()=>setEdit(null)}><X/></button><h2>{edit.id ? 'แก้ไขคำตอบรับ' : 'เพิ่มคำตอบรับ'}</h2><RsvpForm admin initial={edit} onCancel={()=>setEdit(null)} onSubmit={async data=>{await adminSave(data,edit.id);setEdit(null);await load();}}/></section></div>}
    {deleting && <div className="modal-backdrop"><section className="share-modal" role="dialog" aria-modal="true" aria-label="ยืนยันลบคำตอบ"><h2>ลบคำตอบรับ?</h2><p>ลบรายการของ {deleting.full_name}<br/>การลบนี้ไม่สามารถย้อนกลับได้</p><div className="form-actions"><button autoFocus className="button secondary" disabled={deleteBusy} onClick={()=>setDeleting(null)}>ยกเลิก</button><button className="button danger" disabled={deleteBusy} onClick={async()=>{setDeleteBusy(true);try{await adminDelete(deleting.id);setDeleting(null);await load();}catch{setError('ลบไม่สำเร็จ กรุณาลองใหม่');setDeleting(null);}finally{setDeleteBusy(false);}}}>{deleteBusy ? 'กำลังลบ…' : 'ยืนยันลบ'}</button></div></section></div>}
  </div>;
}
